
package com.nju.groupPurchaseManagementSystem.smsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SMSender", targetNamespace = "http://assignment3/", wsdlLocation = "http://localhost:8080/SMSender?wsdl")
public class SMSender
    extends Service
{

    private final static URL SMSENDER_WSDL_LOCATION;
    private final static WebServiceException SMSENDER_EXCEPTION;
    private final static QName SMSENDER_QNAME = new QName("http://assignment3/", "SMSender");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SMSender?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSENDER_WSDL_LOCATION = url;
        SMSENDER_EXCEPTION = e;
    }

    public SMSender() {
        super(__getWsdlLocation(), SMSENDER_QNAME);
    }

    public SMSender(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSENDER_QNAME, features);
    }

    public SMSender(URL wsdlLocation) {
        super(wsdlLocation, SMSENDER_QNAME);
    }

    public SMSender(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSENDER_QNAME, features);
    }

    public SMSender(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSender(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShortMessageSender
     */
    @WebEndpoint(name = "SMSenderImplPort")
    public ShortMessageSender getSMSenderImplPort() {
        return super.getPort(new QName("http://assignment3/", "SMSenderImplPort"), ShortMessageSender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShortMessageSender
     */
    @WebEndpoint(name = "SMSenderImplPort")
    public ShortMessageSender getSMSenderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignment3/", "SMSenderImplPort"), ShortMessageSender.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSENDER_EXCEPTION!= null) {
            throw SMSENDER_EXCEPTION;
        }
        return SMSENDER_WSDL_LOCATION;
    }

}
