// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "RSCorba.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



RsInterface::RetailSystemService_ptr RsInterface::RetailSystemService_Helper::_nil() {
  return ::RsInterface::RetailSystemService::_nil();
}

::CORBA::Boolean RsInterface::RetailSystemService_Helper::is_nil(::RsInterface::RetailSystemService_ptr p) {
  return ::CORBA::is_nil(p);

}

void RsInterface::RetailSystemService_Helper::release(::RsInterface::RetailSystemService_ptr p) {
  ::CORBA::release(p);
}

void RsInterface::RetailSystemService_Helper::marshalObjRef(::RsInterface::RetailSystemService_ptr obj, cdrStream& s) {
  ::RsInterface::RetailSystemService::_marshalObjRef(obj, s);
}

RsInterface::RetailSystemService_ptr RsInterface::RetailSystemService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::RsInterface::RetailSystemService::_unmarshalObjRef(s);
}

void RsInterface::RetailSystemService_Helper::duplicate(::RsInterface::RetailSystemService_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

RsInterface::RetailSystemService_ptr
RsInterface::RetailSystemService::_duplicate(::RsInterface::RetailSystemService_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

RsInterface::RetailSystemService_ptr
RsInterface::RetailSystemService::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


RsInterface::RetailSystemService_ptr
RsInterface::RetailSystemService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

RsInterface::RetailSystemService_ptr
RsInterface::RetailSystemService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RetailSystemService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RetailSystemService* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_RetailSystemService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* RsInterface::RetailSystemService::_PD_repoId = "IDL:RsInterface/RetailSystemService:1.0";


RsInterface::_objref_RetailSystemService::~_objref_RetailSystemService() {
  
}


RsInterface::_objref_RetailSystemService::_objref_RetailSystemService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::RsInterface::RetailSystemService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
RsInterface::_objref_RetailSystemService::_ptrToObjRef(const char* id)
{
  if( id == ::RsInterface::RetailSystemService::_PD_repoId )
    return (::RsInterface::RetailSystemService_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::RsInterface::RetailSystemService::_PD_repoId) )
    return (::RsInterface::RetailSystemService_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring
class _0RL_cd_C67295F43E024466_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_C67295F43E024466_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_C67295F43E024466_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_C67295F43E024466_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_C67295F43E024466_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_C67295F43E024466_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_C67295F43E024466_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_C67295F43E024466_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_C67295F43E024466_00000000* tcd = (_0RL_cd_C67295F43E024466_00000000*)cd;
  RsInterface::_impl_RetailSystemService* impl = (RsInterface::_impl_RetailSystemService*) svnt->_ptrToInterface(RsInterface::RetailSystemService::_PD_repoId);
  tcd->result = impl->confirmPurchase(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean RsInterface::_objref_RetailSystemService::confirmPurchase(const char* sk, const char* confirmCode)
{
  _0RL_cd_C67295F43E024466_00000000 _call_desc(_0RL_lcfn_C67295F43E024466_10000000, "confirmPurchase", 16);
  _call_desc.arg_0 = sk;
  _call_desc.arg_1 = confirmCode;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_cstring_i_cdouble_i_clong
class _0RL_cd_C67295F43E024466_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_C67295F43E024466_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Double arg_3;
  ::CORBA::Long arg_4;
  ::CORBA::Boolean result;
};

void _0RL_cd_C67295F43E024466_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);
  arg_3 >>= _n;
  arg_4 >>= _n;

}

void _0RL_cd_C67295F43E024466_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();
  (::CORBA::Double&)arg_3 <<= _n;
  (::CORBA::Long&)arg_4 <<= _n;

}

void _0RL_cd_C67295F43E024466_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_C67295F43E024466_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_C67295F43E024466_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_C67295F43E024466_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_C67295F43E024466_20000000* tcd = (_0RL_cd_C67295F43E024466_20000000*)cd;
  RsInterface::_impl_RetailSystemService* impl = (RsInterface::_impl_RetailSystemService*) svnt->_ptrToInterface(RsInterface::RetailSystemService::_PD_repoId);
  tcd->result = impl->publishGroupPurchaseItem(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4);


}

::CORBA::Boolean RsInterface::_objref_RetailSystemService::publishGroupPurchaseItem(const char* sk, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit)
{
  _0RL_cd_C67295F43E024466_20000000 _call_desc(_0RL_lcfn_C67295F43E024466_30000000, "publishGroupPurchaseItem", 25);
  _call_desc.arg_0 = sk;
  _call_desc.arg_1 = productName;
  _call_desc.arg_2 = introduction;
  _call_desc.arg_3 = price;
  _call_desc.arg_4 = limit;

  _invoke(_call_desc);
  return _call_desc.result;


}
RsInterface::_pof_RetailSystemService::~_pof_RetailSystemService() {}


omniObjRef*
RsInterface::_pof_RetailSystemService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::RsInterface::_objref_RetailSystemService(ior, id);
}


::CORBA::Boolean
RsInterface::_pof_RetailSystemService::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::RsInterface::RetailSystemService::_PD_repoId) )
    return 1;
  
  return 0;
}

const RsInterface::_pof_RetailSystemService _the_pof_RsInterface_mRetailSystemService;

RsInterface::_impl_RetailSystemService::~_impl_RetailSystemService() {}


::CORBA::Boolean
RsInterface::_impl_RetailSystemService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "confirmPurchase") ) {

    _0RL_cd_C67295F43E024466_00000000 _call_desc(_0RL_lcfn_C67295F43E024466_10000000, "confirmPurchase", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "publishGroupPurchaseItem") ) {

    _0RL_cd_C67295F43E024466_20000000 _call_desc(_0RL_lcfn_C67295F43E024466_30000000, "publishGroupPurchaseItem", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
RsInterface::_impl_RetailSystemService::_ptrToInterface(const char* id)
{
  if( id == ::RsInterface::RetailSystemService::_PD_repoId )
    return (::RsInterface::_impl_RetailSystemService*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::RsInterface::RetailSystemService::_PD_repoId) )
    return (::RsInterface::_impl_RetailSystemService*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
RsInterface::_impl_RetailSystemService::_mostDerivedRepoId()
{
  return ::RsInterface::RetailSystemService::_PD_repoId;
}

POA_RsInterface::RetailSystemService::~RetailSystemService() {}

