// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __retailSystem_hh__
#define __retailSystem_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr

#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr

#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE RsInterface

_CORBA_MODULE_BEG

#ifndef __RsInterface_mRetailSystemService__
#define __RsInterface_mRetailSystemService__

  class RetailSystemService;
  class _objref_RetailSystemService;
  class _impl_RetailSystemService;
  
  typedef _objref_RetailSystemService* RetailSystemService_ptr;
  typedef RetailSystemService_ptr RetailSystemServiceRef;

  class RetailSystemService_Helper {
  public:
    typedef RetailSystemService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_RetailSystemService, RetailSystemService_Helper> RetailSystemService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_RetailSystemService,RetailSystemService_Helper > RetailSystemService_out;

#endif

  // interface RetailSystemService
  class RetailSystemService {
  public:
    // Declarations for this interface type.
    typedef RetailSystemService_ptr _ptr_type;
    typedef RetailSystemService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_RetailSystemService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean confirmPurchase(const char* sk, const char* confirmCode);
    ::CORBA::Boolean publishGroupPurchaseItem(const char* sk, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit);

    inline _objref_RetailSystemService()  { _PR_setobj(0); }  // nil
    _objref_RetailSystemService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_RetailSystemService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_RetailSystemService(const _objref_RetailSystemService&);
    _objref_RetailSystemService& operator = (const _objref_RetailSystemService&);
    // not implemented

    friend class RetailSystemService;
  };

  class _pof_RetailSystemService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_RetailSystemService() : _OMNI_NS(proxyObjectFactory)(RetailSystemService::_PD_repoId) {}
    virtual ~_pof_RetailSystemService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_RetailSystemService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_RetailSystemService();

    virtual ::CORBA::Boolean confirmPurchase(const char* sk, const char* confirmCode) = 0;
    virtual ::CORBA::Boolean publishGroupPurchaseItem(const char* sk, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_RsInterface
_CORBA_MODULE_BEG

  class RetailSystemService :
    public virtual RsInterface::_impl_RetailSystemService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~RetailSystemService();

    inline ::RsInterface::RetailSystemService_ptr _this() {
      return (::RsInterface::RetailSystemService_ptr) _do_this(::RsInterface::RetailSystemService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_RsInterface
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
RsInterface::RetailSystemService::_marshalObjRef(::RsInterface::RetailSystemService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_retailSystem
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_retailSystem
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_retailSystem
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_retailSystem
#endif

#endif  // __retailSystem_hh__

