module Bank {

	valuetype record {
		public string source;
		public string target;
		public double amount;
	};

	typedef sequence<record> recordList;
    typedef sequence<string> recordListString;

	interface BankService{
		recordList listHistory( in string account, in string password);
		recordListString listInListString( in string account, in string password);
	};
};